server:
  port: 9191
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: APIGATEWAY    
  cloud:
   gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE
        predicates:        - Path=/user/**
        filters:
          - name: CircuitBreaker
            args:
              name: USERSERVICE
              fallbackUri: forward:/userServiceFallBack
               
        
      - id: DEPARTMENTSERVICE
        uri: lb://DEPARTMENTSERVICE
        predicates:
        - Path=/department/**
        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENTSERVICE
              fallbackUri: forward:/departmentServiceFallBack
        
        
#actuator

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
        

# RESILIENCE4J PROPERTIES
resilience4j:
  circuitbreaker:
    configs:
      default:
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        wait-duration-in-open-state: 2000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      USERSERVICE:
        baseConfig: default
        ringBufferSizeInClosedState: 5
      DEPARTMENTSERVICE:
        baseConfig: default
        ringBufferSizeInClosedState: 5
            




    
    